#!/bin/sh
#Post Install Script

#cp /opt/mirrorcast/receivers ~/receivers
#cp /tmp/receivers.back ~/receivers

#Install http-server
npm install http-server -g

#Set up nbd server
echo "Editing permissions of nbd-server, if you use this for something else you might want to change this manually."
sed -i 's,user,\# &,' config
sed -i 's,group,\# &,' config
sudo systemctl enable nbd-server
sudo service nbd-server restart
exit 0
